version: "2"

services:
  web:
    build: .
    command: python main.py
    volumes:
      - .:/code
    ports:
      - "80:8000"
    depends_on:
      - db
      
  db:
    image: rethinkdb
    ports:
      - "8080:8080"